
import { Product, Category } from "./types";

// Categories
export const categories: Category[] = [
  {
    id: "outfits",
    name: "Western Outfits",
    image: "/placeholder.svg",
    subcategories: [
      { id: "mens", name: "Men's Wear" },
      { id: "womens", name: "Women's Wear" },
    ],
  },
  {
    id: "shoes",
    name: "Western Shoes",
    image: "/placeholder.svg",
    subcategories: [
      { id: "boots", name: "Boots" },
      { id: "loafers", name: "Loafers" },
    ],
  },
  {
    id: "watches",
    name: "Luxury Watches",
    image: "/placeholder.svg",
  },
  {
    id: "accessories",
    name: "Accessories",
    image: "/placeholder.svg",
    subcategories: [
      { id: "hats", name: "Hats" },
      { id: "belts", name: "Belts" },
      { id: "jewelry", name: "Jewelry" },
    ],
  },
];

// Products
export const products: Product[] = [
  // Men's Outfits
  {
    id: "mens-denim-shirt-1",
    name: "Premium Denim Shirt",
    description: "Classic denim shirt with pearl buttons and western styling.",
    price: 3499,
    image: "/placeholder.svg",
    category: "outfits",
    subcategory: "mens",
    featured: true,
    colors: ["Blue", "Dark Blue", "Black"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    inStock: true,
  },
  {
    id: "mens-leather-jacket-1",
    name: "Vintage Leather Jacket",
    description: "Premium cowhide leather jacket with authentic western detailing.",
    price: 12999,
    image: "/placeholder.svg",
    category: "outfits",
    subcategory: "mens",
    bestSeller: true,
    colors: ["Brown", "Black"],
    sizes: ["M", "L", "XL", "XXL"],
    inStock: true,
  },
  {
    id: "mens-denim-jeans-1",
    name: "Authentic Western Jeans",
    description: "Rugged denim jeans with classic western cut and detailing.",
    price: 4999,
    image: "/placeholder.svg",
    category: "outfits",
    subcategory: "mens",
    colors: ["Blue", "Black", "Grey"],
    sizes: ["30", "32", "34", "36", "38", "40"],
    inStock: true,
  },
  {
    id: "mens-plaid-shirt-1",
    name: "Classic Plaid Shirt",
    description: "Traditional western plaid shirt with snap buttons.",
    price: 2999,
    image: "/placeholder.svg",
    category: "outfits",
    subcategory: "mens",
    colors: ["Red", "Blue", "Green"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    inStock: true,
  },
  {
    id: "mens-vest-1",
    name: "Leather Western Vest",
    description: "Genuine leather vest with intricate western embroidery.",
    price: 5999,
    image: "/placeholder.svg",
    category: "outfits",
    subcategory: "mens",
    featured: true,
    colors: ["Brown", "Black"],
    sizes: ["M", "L", "XL", "XXL"],
    inStock: true,
  },
  {
    id: "mens-blazer-1",
    name: "Western Style Blazer",
    description: "Elegant blazer with western-inspired embellishments.",
    price: 8999,
    image: "/placeholder.svg",
    category: "outfits",
    subcategory: "mens",
    new: true,
    colors: ["Navy", "Black", "Burgundy"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    inStock: true,
  },
  
  // Women's Outfits
  {
    id: "womens-denim-dress-1",
    name: "Denim Western Dress",
    description: "Flattering denim dress with western-inspired detailing.",
    price: 5499,
    image: "/placeholder.svg",
    category: "outfits",
    subcategory: "womens",
    featured: true,
    colors: ["Blue", "Light Blue"],
    sizes: ["XS", "S", "M", "L", "XL"],
    inStock: true,
  },
  {
    id: "womens-leather-jacket-1",
    name: "Women's Fringe Leather Jacket",
    description: "Luxurious leather jacket with elegant fringe detailing.",
    price: 11999,
    image: "/placeholder.svg",
    category: "outfits",
    subcategory: "womens",
    bestSeller: true,
    colors: ["Brown", "Tan", "Black"],
    sizes: ["S", "M", "L", "XL"],
    inStock: true,
  },
  {
    id: "womens-denim-skirt-1",
    name: "Western Denim Skirt",
    description: "Classic A-line denim skirt with western-style embroidery.",
    price: 3999,
    image: "/placeholder.svg",
    category: "outfits",
    subcategory: "womens",
    colors: ["Blue", "Black"],
    sizes: ["XS", "S", "M", "L", "XL"],
    inStock: true,
  },
  {
    id: "womens-blouse-1",
    name: "Embroidered Western Blouse",
    description: "Light cotton blouse with intricate western embroidery.",
    price: 2799,
    image: "/placeholder.svg",
    category: "outfits",
    subcategory: "womens",
    new: true,
    colors: ["White", "Beige", "Light Blue"],
    sizes: ["XS", "S", "M", "L", "XL"],
    inStock: true,
  },
  {
    id: "womens-vest-1",
    name: "Women's Leather Vest",
    description: "Elegant leather vest with decorative western stitching.",
    price: 4999,
    image: "/placeholder.svg",
    category: "outfits",
    subcategory: "womens",
    colors: ["Brown", "Black", "Burgundy"],
    sizes: ["S", "M", "L", "XL"],
    inStock: true,
  },
  {
    id: "womens-jeans-1",
    name: "Western Cut Jeans",
    description: "Flattering bootcut jeans with authentic western styling.",
    price: 4599,
    image: "/placeholder.svg",
    category: "outfits",
    subcategory: "womens",
    colors: ["Blue", "Black", "Grey"],
    sizes: ["25", "26", "27", "28", "29", "30", "31", "32"],
    inStock: true,
  },
  
  // Boots & Shoes
  {
    id: "boots-cowboy-1",
    name: "Classic Cowboy Boots",
    description: "Authentic leather cowboy boots with traditional stitching.",
    price: 8999,
    image: "/placeholder.svg",
    category: "shoes",
    subcategory: "boots",
    featured: true,
    bestSeller: true,
    colors: ["Brown", "Black", "Tan"],
    sizes: ["7", "8", "9", "10", "11", "12"],
    inStock: true,
  },
  {
    id: "boots-riding-1",
    name: "Leather Riding Boots",
    description: "Premium leather riding boots with durable construction.",
    price: 11999,
    image: "/placeholder.svg",
    category: "shoes",
    subcategory: "boots",
    colors: ["Brown", "Black"],
    sizes: ["7", "8", "9", "10", "11", "12"],
    inStock: true,
  },
  {
    id: "boots-western-1",
    name: "Embellished Western Boots",
    description: "Decorative western boots with intricate embroidery.",
    price: 13999,
    image: "/placeholder.svg",
    category: "shoes",
    subcategory: "boots",
    new: true,
    colors: ["Brown", "Black", "Red"],
    sizes: ["7", "8", "9", "10", "11", "12"],
    inStock: true,
  },
  {
    id: "boots-ankle-1",
    name: "Western Ankle Boots",
    description: "Stylish ankle boots with western-inspired detailing.",
    price: 7999,
    image: "/placeholder.svg",
    category: "shoes",
    subcategory: "boots",
    colors: ["Brown", "Black", "Tan"],
    sizes: ["7", "8", "9", "10", "11", "12"],
    inStock: true,
  },
  {
    id: "loafers-western-1",
    name: "Western Moccasin Loafers",
    description: "Comfortable moccasin loafers with western fringe details.",
    price: 5999,
    image: "/placeholder.svg",
    category: "shoes",
    subcategory: "loafers",
    colors: ["Brown", "Tan", "Black"],
    sizes: ["7", "8", "9", "10", "11", "12"],
    inStock: true,
  },
  {
    id: "loafers-suede-1",
    name: "Suede Western Loafers",
    description: "Premium suede loafers with decorative western accents.",
    price: 6499,
    image: "/placeholder.svg",
    category: "shoes",
    subcategory: "loafers",
    colors: ["Tan", "Blue", "Brown"],
    sizes: ["7", "8", "9", "10", "11", "12"],
    inStock: true,
  },
  
  // Luxury Watches
  {
    id: "watch-leather-1",
    name: "Western Heritage Timepiece",
    description: "Exquisite watch with leather strap and western motif face.",
    price: 24999,
    image: "/placeholder.svg",
    category: "watches",
    featured: true,
    colors: ["Brown", "Black"],
    inStock: true,
  },
  {
    id: "watch-gold-1",
    name: "Gold Western Elite Watch",
    description: "Luxurious gold-plated watch with intricate western engravings.",
    price: 34999,
    image: "/placeholder.svg",
    category: "watches",
    bestSeller: true,
    inStock: true,
  },
  {
    id: "watch-silver-1",
    name: "Silver Frontier Chronograph",
    description: "Silver chronograph watch with western-inspired details.",
    price: 29999,
    image: "/placeholder.svg",
    category: "watches",
    new: true,
    inStock: true,
  },
  {
    id: "watch-vintage-1",
    name: "Vintage Pocket Watch",
    description: "Classic western-style pocket watch with chain.",
    price: 18999,
    image: "/placeholder.svg",
    category: "watches",
    inStock: true,
  },
  {
    id: "watch-leather-2",
    name: "Embossed Leather Watch",
    description: "Elegant watch with embossed leather strap and western design.",
    price: 21999,
    image: "/placeholder.svg",
    category: "watches",
    colors: ["Dark Brown", "Black", "Burgundy"],
    inStock: true,
  },
  {
    id: "watch-bronze-1",
    name: "Bronze Western Timepiece",
    description: "Rugged bronze watch with western countryside motif.",
    price: 23999,
    image: "/placeholder.svg",
    category: "watches",
    inStock: true,
  },
  
  // Hats
  {
    id: "hat-cowboy-1",
    name: "Classic Cowboy Hat",
    description: "Authentic cowboy hat made from premium felt.",
    price: 7999,
    image: "/placeholder.svg",
    category: "accessories",
    subcategory: "hats",
    featured: true,
    colors: ["Brown", "Black", "Tan"],
    sizes: ["S", "M", "L", "XL"],
    inStock: true,
  },
  {
    id: "hat-straw-1",
    name: "Western Straw Hat",
    description: "Lightweight straw hat perfect for sunny days.",
    price: 4999,
    image: "/placeholder.svg",
    category: "accessories",
    subcategory: "hats",
    colors: ["Natural", "White", "Tan"],
    sizes: ["S", "M", "L", "XL"],
    inStock: true,
  },
  {
    id: "hat-leather-1",
    name: "Leather Western Hat",
    description: "Durable leather hat with decorative band.",
    price: 8999,
    image: "/placeholder.svg",
    category: "accessories",
    subcategory: "hats",
    colors: ["Brown", "Black"],
    sizes: ["S", "M", "L", "XL"],
    inStock: true,
  },
  
  // Belts
  {
    id: "belt-leather-1",
    name: "Classic Western Belt",
    description: "Handcrafted leather belt with ornate western buckle.",
    price: 3999,
    image: "/placeholder.svg",
    category: "accessories",
    subcategory: "belts",
    featured: true,
    bestSeller: true,
    colors: ["Brown", "Black", "Tan"],
    sizes: ["32", "34", "36", "38", "40", "42"],
    inStock: true,
  },
  {
    id: "belt-studded-1",
    name: "Studded Western Belt",
    description: "Eye-catching belt with decorative studs and embossing.",
    price: 4499,
    image: "/placeholder.svg",
    category: "accessories",
    subcategory: "belts",
    colors: ["Brown", "Black"],
    sizes: ["32", "34", "36", "38", "40", "42"],
    inStock: true,
  },
  {
    id: "belt-tooled-1",
    name: "Hand-Tooled Leather Belt",
    description: "Premium leather belt with intricate hand-tooled designs.",
    price: 5999,
    image: "/placeholder.svg",
    category: "accessories",
    subcategory: "belts",
    colors: ["Brown", "Tan"],
    sizes: ["32", "34", "36", "38", "40", "42"],
    inStock: true,
  },
  
  // Jewelry
  {
    id: "jewelry-necklace-1",
    name: "Silver Concho Necklace",
    description: "Sterling silver necklace with authentic western concho pendant.",
    price: 6999,
    image: "/placeholder.svg",
    category: "accessories",
    subcategory: "jewelry",
    featured: true,
    inStock: true,
  },
  {
    id: "jewelry-bracelet-1",
    name: "Leather & Silver Bracelet",
    description: "Braided leather bracelet with sterling silver accents.",
    price: 3499,
    image: "/placeholder.svg",
    category: "accessories",
    subcategory: "jewelry",
    colors: ["Brown", "Black"],
    inStock: true,
  },
  {
    id: "jewelry-earrings-1",
    name: "Western Motif Earrings",
    description: "Elegant earrings featuring classic western designs.",
    price: 2999,
    image: "/placeholder.svg",
    category: "accessories",
    subcategory: "jewelry",
    new: true,
    inStock: true,
  },
  {
    id: "jewelry-bolo-1",
    name: "Traditional Bolo Tie",
    description: "Classic bolo tie with ornate western slider.",
    price: 3999,
    image: "/placeholder.svg",
    category: "accessories",
    subcategory: "jewelry",
    inStock: true,
  },
  
  // More products to reach 48+
  {
    id: "mens-shirt-2",
    name: "Embroidered Western Shirt",
    description: "Premium shirt with decorative western embroidery.",
    price: 4499,
    image: "/placeholder.svg",
    category: "outfits",
    subcategory: "mens",
    colors: ["White", "Black", "Blue"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    inStock: true,
  },
  {
    id: "womens-jacket-2",
    name: "Suede Western Jacket",
    description: "Soft suede jacket with western fringe details.",
    price: 9999,
    image: "/placeholder.svg",
    category: "outfits",
    subcategory: "womens",
    colors: ["Tan", "Brown", "Black"],
    sizes: ["S", "M", "L", "XL"],
    inStock: true,
  },
  {
    id: "boots-exotic-1",
    name: "Exotic Leather Western Boots",
    description: "Premium boots made from exotic leather with unique patterns.",
    price: 16999,
    image: "/placeholder.svg",
    category: "shoes",
    subcategory: "boots",
    colors: ["Brown", "Black"],
    sizes: ["7", "8", "9", "10", "11", "12"],
    inStock: true,
  },
  {
    id: "watch-limited-1",
    name: "Limited Edition Western Watch",
    description: "Exclusive watch with numbered limited edition certificate.",
    price: 49999,
    image: "/placeholder.svg",
    category: "watches",
    inStock: true,
  },
  {
    id: "hat-felt-1",
    name: "Premium Felt Western Hat",
    description: "Luxurious felt hat with decorative band and feather.",
    price: 9999,
    image: "/placeholder.svg",
    category: "accessories",
    subcategory: "hats",
    colors: ["Black", "Gray", "Brown"],
    sizes: ["S", "M", "L", "XL"],
    inStock: true,
  },
  {
    id: "mens-coat-1",
    name: "Western Duster Coat",
    description: "Traditional long duster coat for the authentic western look.",
    price: 13999,
    image: "/placeholder.svg",
    category: "outfits",
    subcategory: "mens",
    colors: ["Brown", "Black", "Tan"],
    sizes: ["M", "L", "XL", "XXL"],
    inStock: true,
  },
  {
    id: "womens-hat-1",
    name: "Women's Western Hat",
    description: "Elegantly styled hat with decorative band for women.",
    price: 6999,
    image: "/placeholder.svg",
    category: "accessories",
    subcategory: "hats",
    colors: ["Brown", "Black", "White"],
    sizes: ["S", "M", "L"],
    inStock: true,
  },
  {
    id: "jewelry-ring-1",
    name: "Western Silver Ring",
    description: "Sterling silver ring with turquoise stone and western motifs.",
    price: 4499,
    image: "/placeholder.svg",
    category: "accessories",
    subcategory: "jewelry",
    sizes: ["6", "7", "8", "9", "10", "11"],
    inStock: true,
  },
  {
    id: "boots-work-1",
    name: "Western Work Boots",
    description: "Durable work boots with western styling and safety features.",
    price: 9499,
    image: "/placeholder.svg",
    category: "shoes",
    subcategory: "boots",
    colors: ["Brown", "Tan"],
    sizes: ["7", "8", "9", "10", "11", "12"],
    inStock: true,
  },
  {
    id: "watch-diamond-1",
    name: "Diamond Accented Western Watch",
    description: "Luxurious watch with genuine diamond accents and western styling.",
    price: 59999,
    image: "/placeholder.svg",
    category: "watches",
    inStock: true,
  },
  {
    id: "mens-suit-1",
    name: "Western Style Suit",
    description: "Complete suit with western-inspired details and tailoring.",
    price: 19999,
    image: "/placeholder.svg",
    category: "outfits",
    subcategory: "mens",
    colors: ["Black", "Navy", "Gray"],
    sizes: ["40", "42", "44", "46", "48"],
    inStock: true,
  },
  {
    id: "womens-boots-1",
    name: "Women's Western Boots",
    description: "Stylish western boots designed specifically for women.",
    price: 8499,
    image: "/placeholder.svg",
    category: "shoes",
    subcategory: "boots",
    colors: ["Brown", "Black", "Red"],
    sizes: ["5", "6", "7", "8", "9", "10"],
    inStock: true,
  },
  {
    id: "belt-buckle-1",
    name: "Collectible Western Buckle",
    description: "Ornate western belt buckle with detailed craftsmanship.",
    price: 2999,
    image: "/placeholder.svg",
    category: "accessories",
    subcategory: "belts",
    inStock: true,
  },
];

// Format price in Indian Rupees
export function formatPrice(price: number): string {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(price);
}

// Get products by category
export function getProductsByCategory(category: string, subcategory?: string): Product[] {
  if (subcategory) {
    return products.filter(
      (product) => product.category === category && product.subcategory === subcategory
    );
  }
  return products.filter((product) => product.category === category);
}

// Get featured products
export function getFeaturedProducts(): Product[] {
  return products.filter((product) => product.featured);
}

// Get best seller products
export function getBestSellerProducts(): Product[] {
  return products.filter((product) => product.bestSeller);
}

// Get new arrivals
export function getNewArrivals(): Product[] {
  return products.filter((product) => product.new);
}

// Get product by ID
export function getProductById(id: string): Product | undefined {
  return products.find((product) => product.id === id);
}
